import assert from "node:assert/strict";
import { mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";

import type { PrismaClient } from "@anneal/db";

import { createApp } from "./test-app.js";

// Captured from the route registration table on the chain base before the
// per-prefix split. Middleware entries (method ALL) are intentionally omitted.
const expectedRoutes = [
  "GET /",
  "GET /health",
  "GET /version",
  "GET /runners",
  "POST /hooks/templates/:templateId",
  "GET /files",
  "GET /files/content",
  "PUT /files/content",
  "POST /files/mkdir",
  "POST /files/move",
  "DELETE /files",
  "GET /onboarding",
  "POST /onboarding",
  "GET /projects",
  "POST /projects",
  "GET /projects/:projectId",
  "PATCH /projects/:projectId",
  "DELETE /projects/:projectId",
  "GET /projects/:projectId/costs",
  "GET /projects/:projectId/environments",
  "POST /projects/:projectId/environments",
  "GET /environments/:environmentId",
  "PATCH /environments/:environmentId",
  "DELETE /environments/:environmentId",
  "GET /secrets",
  "POST /secrets",
  "GET /secrets/:secretId",
  "PATCH /secrets/:secretId",
  "DELETE /secrets/:secretId",
  "GET /projects/:projectId/agents",
  "POST /projects/:projectId/agents",
  "GET /agents/:agentId",
  "PATCH /agents/:agentId",
  "POST /agents/:agentId/reset-runtime-config",
  "DELETE /agents/:agentId",
  "POST /agents/:agentId/archive",
  "POST /agents/:agentId/unarchive",
  "POST /agents/:agentId/duplicate",
  "GET /agents/:agentId/secret-grants",
  "POST /agents/:agentId/secret-grants",
  "DELETE /agents/:agentId/secret-grants/:secretId/:envVar",
  "GET /agents/:agentId/filesystem-grants",
  "POST /agents/:agentId/filesystem-grants",
  "PATCH /agents/:agentId/filesystem-grants/:grantId",
  "DELETE /agents/:agentId/filesystem-grants/:grantId",
  "POST /agents/:agentId/collaborators",
  "DELETE /agents/:agentId/collaborators/:allowedAgentId",
  "GET /projects/:projectId/skills",
  "POST /projects/:projectId/skills",
  "POST /agents/:agentId/skills",
  "DELETE /agents/:agentId/skills/:skillId",
  "GET /projects/:projectId/mcp-connections",
  "POST /projects/:projectId/mcp-connections",
  "POST /agents/:agentId/mcp-connections",
  "DELETE /agents/:agentId/mcp-connections/:connectionId",
  "GET /projects/:projectId/repos",
  "POST /projects/:projectId/repos",
  "PATCH /repos/:repoId",
  "DELETE /repos/:repoId",
  "POST /agents/:agentId/repos/:repoId/access",
  "DELETE /agents/:agentId/repos/:repoId/access",
  "GET /projects/:projectId/goals",
  "POST /projects/:projectId/goals",
  "GET /goals/:goalId",
  "PATCH /goals/:goalId",
  "DELETE /goals/:goalId",
  "POST /goals/:goalId/approve-dod",
  "POST /goals/:goalId/pause",
  "GET /goals/:goalId/definition-of-done",
  "POST /goals/:goalId/definition-of-done",
  "PATCH /goals/:goalId/definition-of-done/:itemId",
  "DELETE /goals/:goalId/definition-of-done/:itemId",
  "GET /goals/:goalId/progress-log",
  "POST /goals/:goalId/progress-log",
  "GET /projects/:projectId/task-templates",
  "GET /task-templates/:templateId",
  "POST /projects/:projectId/task-templates/:templateId/clone",
  "PUT /projects/:projectId/task-templates/:templateId/steps",
  "PATCH /task-templates/:templateId",
  "POST /projects/:projectId/task-templates/:templateId/instantiate",
  "GET /projects/:projectId/triggers",
  "GET /triggers/:templateId",
  "GET /triggers/:templateId/fires",
  "POST /triggers/:templateId/pause",
  "POST /triggers/:templateId/enable",
  "POST /task-templates/:templateId/fire",
  "GET /projects/:projectId/task-templates/:templateId/staffing-profiles",
  "POST /projects/:projectId/task-templates/:templateId/staffing-profiles",
  "PUT /staffing-profiles/:profileId",
  "PATCH /staffing-profiles/:profileId",
  "DELETE /staffing-profiles/:profileId",
  "POST /staffing-profiles/:profileId/reset",
  "GET /tasks",
  "POST /projects/:projectId/tasks",
  "GET /tasks/:taskId",
  "GET /tasks/:taskId/startability",
  "GET /tasks/:taskId/chain",
  "POST /tasks/:taskId/chain/hold",
  "POST /tasks/:taskId/chain/resume",
  "POST /tasks/:taskId/merge-tail/repair",
  "PATCH /tasks/:taskId",
  "DELETE /tasks/:taskId/chain",
  "DELETE /tasks/:taskId",
  "POST /tasks/:taskId/retry",
  "POST /tasks/:taskId/start",
  "POST /tasks/:taskId/archive",
  "POST /tasks/:taskId/unarchive",
  "POST /projects/:projectId/tasks/archive-done",
  "POST /tasks/:taskId/schedule/pause",
  "POST /tasks/:taskId/schedule/resume",
  "GET /tasks/:taskId/recurring-fires",
  "GET /tasks/:taskId/activity",
  "GET /tasks/:taskId/output",
  "PUT /tasks/:taskId/output",
  "POST /tasks/:taskId/merge-target",
  "POST /tasks/:taskId/activity",
  "GET /merge-lease",
  "GET /inbox/messages/summary",
  "GET /inbox/messages",
  "GET /inbox/messages/:messageId",
  "POST /inbox/messages/:messageId/decision",
  "POST /inbox/messages/:messageId/reply",
  "POST /inbox/messages/:messageId/close",
  "POST /runner/availability",
  "POST /runner/preflight",
  "POST /runner/workspaces/reclaimable",
  "POST /runner/workspaces/reclaimed",
  "POST /runner/workspaces/salvaged",
  "POST /runner/tasks/claim",
  "POST /runner/runs/:runId/start",
  "POST /runner/runs/:runId/heartbeat",
  "POST /runner/runs/:runId/cancel/acknowledge",
  "POST /runner/runs/:runId/publication",
  "POST /runner/runs/:runId/cleanup",
  "POST /runner/runs/:runId/events",
  "POST /runner/runs/:runId/activity",
  "POST /session/runs/:runId/activity",
  "GET /session/runs/:runId/chain/steps/:chainIndex/activity",
  "GET /session/runs/:runId/status",
  "PATCH /session/runs/:runId/task",
  "POST /session/runs/:runId/revalidation/cancel",
  "PUT /session/runs/:runId/output",
  "POST /session/runs/:runId/inbox/questions",
  "GET /session/runs/:runId/files",
  "GET /session/runs/:runId/files/content",
  "PUT /session/runs/:runId/files/content",
  "DELETE /session/runs/:runId/files",
  "POST /runner/runs/:runId/complete",
  "GET /sessions",
  "GET /sessions/:sessionId",
  "POST /runs/:runId/cancel",
  "GET /runs/:runId/events",
] as const;

test("createApp preserves the ordered route table", () => {
  const app = createApp({} as PrismaClient, {
    workspaceRoot: mkdtempSync(join(tmpdir(), "anneal-route-table-")),
  });
  const actual = app.routes
    .filter((route) => route.method !== "ALL")
    .map((route) => `${route.method} ${route.path}`);
  assert.deepEqual(actual, expectedRoutes);
});
