/** Wire shapes as serialised by the control plane (packages/db/prisma/schema.prisma).
 *  Decimal columns arrive as strings, DateTime as ISO strings.
 *
 *  Nothing is declared here. Every shape the console reads is owned by a
 *  contract module in `@anneal/db`, and the routes that produce them are bound
 *  to the same declaration, so a server-side rename reaches this file as a
 *  compile error instead of as a silently absent field. */

export type {
  AssigneeType,
  BoardCard,
  BoardChainActivationState,
  BoardLatestRun,
  BoardMoveTarget,
  BoardTask,
  Chain,
  ChainAggregate,
  ChainActiveRepair,
  ChainAggregateState,
  ChainControl,
  ChainFrontier,
  ChainProgress,
  ChainStep,
  CostsReport,
  ExecutionOwner,
  MergeOutcome,
  MergeRecovery,
  RecurringFire,
  Run,
  RunMetrics,
  RunPhaseMetrics,
  RunStatus,
  RunTerminationMetrics,
  RunTokenMetrics,
  RunToolMetrics,
  RunToolNameMetrics,
  ScheduleKind,
  Session,
  TaskActivity,
  TaskDetail,
  TaskList,
  TaskMoveTarget,
  TaskSource,
  TaskStartability,
  TaskStatus,
  TaskStepOutput,
  Trigger,
  TriggerDetail,
  TriggerFire,
  UsageCost,
} from "@anneal/db/board-contract";
export type {
  Agent,
  AgentRepoAccess,
  CodexServiceTier,
  Environment,
  FailureClass,
  FilesystemGrant,
  GoalStatus,
  InboxDeliveryStatus,
  InboxKind,
  InboxStatus,
  MCPConnection,
  Project,
  Repo,
  RepoPermission,
  RunnerKind,
  RunnerPreference,
  Secret,
  SecretPurpose,
  SessionExecutionStatus,
  Skill,
} from "@anneal/db/wire-contract";
export type {
  BackendStatus,
  DaemonStatus,
  Goal,
  GoalDefinitionItem,
  GoalProgressEntry,
  Health,
  InboxChoice,
  InboxDecision,
  InboxMessage,
  InboxReply,
  InboxSummary,
  OnboardingDisclosure,
  OnboardingInstallation,
  OnboardingStatus,
  RunnersResponse,
  SessionEvent,
  SessionEventSource,
  StaffingProfile,
  StaffingProfileEntry,
  StaffingProfileEntryInput,
  StaffingProfileResponse,
  StaffingProfileWarning,
  TaskTemplate,
  TaskTemplateStep,
  VersionInfo,
} from "@anneal/db/console-contract";
